=== ppjsand/pyteal/src/xml/alertmeta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ibm.com/teal/alertmeta"
	xmlns:tns="http://www.ibm.com/teal/alertmeta" elementFormDefault="qualified">
	<element name="alertMetadata">
		<complexType>
			<sequence>
				<element name="alert" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<all>
							<!--
								Descriptive Message Template - Message to display that describes
								the event. This is the reason for the alert. It can contain
								replacement text. (how does this work?)
							-->
							<element name="description" type="string" minOccurs="0" maxOccurs="1"/>
							<element name="msg_template" type="string" minOccurs="1"
								maxOccurs="1" />
							<!--Recommendation - Recommended action. -->
							<element name="recommendation" type="string" minOccurs="1"
								maxOccurs="1" />
							<!--Urgency - How urgent is the alert.  See restrictions for values. -->
							<element name="urgency" minOccurs="1" maxOccurs="1">
								<simpleType>
									<restriction base="string">
										<enumeration value="I" /> <!-- IMMEDIATE Must take corrective action now -->
										<enumeration value="S" />  <!-- SCHEDULE Schedule corrective action as soon as possible -->
										<enumeration value="N" /> <!-- NORMAL Schedule corrective action during normal working hours -->
										<enumeration value="D" /> <!--  DEFER Corrective action can wait for the next maintenance window -->
										<enumeration value="O" /> <!-- OPTIONAL Corrective action can be taken at any time -->
									</restriction>
								</simpleType>
							</element>
                            <!--Severity - See restrictions for values. -->
                            <element name="severity" minOccurs="1" maxOccurs="1">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="F" /> <!-- FATAL Unrecoverable error has occurred -->
                                        <enumeration value="E" />  <!-- ERROR Unrecoverable error.  Lost of function, but system can still run -->
                                        <enumeration value="W" /> <!-- WARNING Non-critical failure or impending failure -->
                                        <enumeration value="I" /> <!--  INFO Informational message only. No action required -->
                                    </restriction>
                                </simpleType>
                            </element>
							<!--Call Home - true = call home; false = don't call home
							                Default is false -->
							<element name="call_home" minOccurs="0" maxOccurs="1">
                               <simpleType>
                                    <restriction base="string">
                                        <enumeration value="Y" />
                                        <enumeration value="N" /> 
                                    </restriction>
                                </simpleType>
                            </element>
                            <!--Customer Notification - true = notify customer; false = don't notify customer.
                                                        Default is false -->
                            <element name="cust_notification" minOccurs="0" maxOccurs="1">
                               <simpleType>
                                    <restriction base="string">
                                        <enumeration value="Y" />
                                        <enumeration value="N" /> 
                                    </restriction>
                                </simpleType>
                            </element>
                            <!-- FRU Class - Class of the FRU this alert is for -->
                            <element name="fru_class" type="string" minOccurs="0" maxOccurs="1" />
                            <!-- FRU List - List of FRUs this alert can be for -->
                            <element name="fru_list" type="string" minOccurs="0" maxOccurs="1" />
                            <!--  Priority - priority of this alert versus other alerts (smallest is highest priority)-->
                            <element name="priority" type="integer" minOccurs="0" maxOccurs="1" />
						</all>
						<attribute name="id" type="ID" use="required" />
					</complexType>
				</element>

			</sequence>
		</complexType>
	</element>


</schema>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/metadata_test/alert_metadata_03.xml
<?xml version="1.0" encoding="UTF-8"?>


<tns:alertMetadata xmlns:tns="http://www.ibm.com/teal/alertmeta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/teal/alertmeta ../../../../../../xml/alertmeta.xsd ">
  <tns:alert id="Alert01">
    <tns:msg_template>This is Alert 01</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="Alert02">
    <tns:msg_template>This is Alert 02</tns:msg_template>
    <tns:recommendation>Recommend doing something else</tns:recommendation>
    <tns:urgency>S</tns:urgency>
    <tns:severity>E</tns:severity>
    <tns:priority>2</tns:priority>
  </tns:alert>
  <tns:alert id="Alert03">
    <tns:msg_template>This is Alert 03</tns:msg_template>
    <tns:recommendation>Do not do anything</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>E</tns:severity>
    <tns:call_home>Y</tns:call_home>
  </tns:alert>
</tns:alertMetadata>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/metadata_test/alert_metadata_01.xml
<?xml version="1.0" encoding="UTF-8"?>


<tns:alertMetadata xmlns:tns="http://www.ibm.com/teal/alertmeta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/teal/alertmeta ../../../../../../xml/alertmeta.xsd ">
  <tns:alert id="Alert01">
    <tns:msg_template>This is Alert 01</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list> 
    <tns:description>This is a description</tns:description>
  </tns:alert>
</tns:alertMetadata>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/gear_ruleset_test/t027/alert_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>


<tns:alertMetadata xmlns:tns="http://www.ibm.com/teal/alertmeta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/teal/alertmeta ../../../../../../xml/alertmeta.xsd ">
  <tns:alert id="E0000001">
    <tns:msg_template>This is Alert 01</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000002">
    <tns:msg_template>This is Alert 02</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000003">
    <tns:msg_template>This is Alert 03</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000004">
    <tns:msg_template>This is Alert 04</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000005">
    <tns:msg_template>This is Alert 05</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000006">
    <tns:msg_template>This is Alert 06</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000007">
    <tns:msg_template>This is Alert 07</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000008">
    <tns:msg_template>This is Alert 08</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000009">
    <tns:msg_template>This is Alert 09</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000010">
    <tns:msg_template>This is Alert 10</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000011">
    <tns:msg_template>This is Alert 11</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000012">
    <tns:msg_template>This is Alert 12</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
  <tns:alert id="E0000013">
    <tns:msg_template>This is Alert 13</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>  
  <tns:alert id="BD00FFF0">
    <tns:msg_template>This is A failure alert</tns:msg_template>
    <tns:recommendation>Recommend doing something</tns:recommendation>
    <tns:urgency>N</tns:urgency>
    <tns:severity>W</tns:severity>
    <tns:call_home>N</tns:call_home>
    <tns:cust_notification>N</tns:cust_notification>
    <tns:fru_class>fru_class</tns:fru_class>
    <tns:fru_list>fru_list1, fru_list2</tns:fru_list>
  </tns:alert>
</tns:alertMetadata>

=== ppjsand/pyteal/src/data/ibm/gpfs/xml/GPFS_GEAR_alert_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<alertMetadata xmlns:tns="http://www.ibm.com/teal/alertmeta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/teal/alertmeta ../../../../../../xml/alertmeta.xsd ">

  <alert id="GP000006">
    <msg_template>SGMGR takeover</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>50</priority>
  </alert>

  <!-- Begin: Uncomment it if needed
  <alert id="GP000007">
    <msg_template>Node failed</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>50</priority>
  </alert>
  End: Don't forget to uncomment the corresponding lines in GPFS_GEAR_rules.xml as well.  -->

  <alert id="GP00000D">
    <msg_template>Event collection buffer overflow</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>50</priority>
  </alert>


  <alert id="GP000010">
    <msg_template>Storage pool utilization crossed threshold</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>70</priority>
  </alert>


  <alert id="GP000015">
    <msg_template>Long IO time</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>50</priority>
  </alert>


  <alert id="GP000016">
    <msg_template>Recovery group takeover</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>50</priority>
  </alert>


  <alert id="GP000018">
    <msg_template>Recovery group open failed</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>E</severity>
    <urgency>N</urgency>
    <priority>80</priority>
  </alert>


  <alert id="GP000019">
    <msg_template>Recovery group panic</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>E</severity>
    <urgency>N</urgency>
    <priority>80</priority>
  </alert>


  <alert id="GP000020">
    <msg_template>pdisk failed</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>70</priority>
  </alert>


  <alert id="GP000022">
    <msg_template>pdisk needs to be replaced</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>E</severity>
    <urgency>N</urgency>
    <priority>60</priority>
  </alert>


  <alert id="GP000023">
    <msg_template>Pdisk path failed</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>E</severity>
    <urgency>N</urgency>
    <priority>60</priority>
  </alert>


  <alert id="GP000024">
    <msg_template>Declustered array rebuild failed</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>E</severity>
    <urgency>N</urgency>
    <priority>70</priority>
  </alert>


  <alert id="GP000025">
    <msg_template>NSD checksum mismatch</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>W</severity>
    <urgency>N</urgency>
    <priority>60</priority>
  </alert>


  <alert id="GP010002">
    <msg_template>GPFS connector stopped</msg_template>
    <recommendation>Refer to the GPFS Administration and Problem Determination guides to resolve the problem. If the problem cannot be resolved, contact your next level of support.</recommendation>
    <severity>I</severity>
    <urgency>N</urgency>
    <priority>50</priority>
  </alert>

</alertMetadata>
