=== ppjsand/pyteal/src/xml/eventmeta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ibm.com/teal/eventmeta" xmlns:tns="http://www.ibm.com/teal/eventmeta" elementFormDefault="qualified">
    <element name="eventMetadata">
        <complexType><sequence>
    	<element name="event" minOccurs="1" maxOccurs="unbounded">
		<complexType>
			<all>
				<!--Descriptive Message - Message to display that describes the event.  
				                           It must be complete as is.  That is, it cannot contain replaceable text. -->
                <element name="message" type="string" minOccurs="1" maxOccurs="1"/>
                <element name="description" type="string" minOccurs="0" maxOccurs="1"/>
			</all>
			<attribute name="id" type="ID" use="required"/>
		</complexType>
	</element>
	</sequence>
	</complexType>
	</element>
</schema>

=== ppjsand/pyteal/src/data/ibm/ll/xml/LL_GEAR_event_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventMetadata  xmlns:tns="http://www.ibm.com/teal/eventmeta" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
				xsi:schemaLocation="http://www.ibm.com/teal/eventmeta ../../../../../xml/eventmeta.xsd ">
	<event id="LL001000" comp="LL">
		<message>Schedd daemon down</message>
	</event>
	<event id="LL001001" comp="LL">
		<message>Startd daemon down</message>
	</event>
	<event id="LL001003" comp="LL">
		<message>Central Manager down</message>
	</event>
	<event id="LL001004" comp="LL">
		<message>Resource Manager down</message>
	</event>
	<event id="LL001005" comp="LL">
		<message>Region Manager down</message>
	</event>
	<event id="LL002001" comp="LL">
		<message>Job step rejected</message>
	</event>
	<event id="LL002002" comp="LL">
		<message>Job step vacated</message>
	</event>
</eventMetadata>

=== ppjsand/pyteal/src/data/ibm/gpfs/xml/GPFS_GEAR_event_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<eventMetadata  xmlns:tns="http://www.ibm.com/teal/eventmeta" 
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
				xsi:schemaLocation="http://www.ibm.com/teal/eventmeta ../../../../../xml/eventmeta.xsd ">>
	<event id="GP000001" comp="GPFS">
		<message>Filesystem mounted</message>
	</event>
	<event id="GP000002" comp="GPFS">
		<message>Filesystem unmounted</message>
	</event>
	<event id="GP000003" comp="GPFS">
		<message>Disk added</message>
	</event>
	<event id="GP000004" comp="GPFS">
		<message>Disk deleted</message>
	</event>
	<event id="GP000005" comp="GPFS">
		<message>Disk state changed</message>
	</event>
	<event id="GP000006" comp="GPFS">
		<message>SGMGR takeover</message>
	</event>
	<event id="GP000007" comp="GPFS">
		<message>Node failed</message>
	</event>
	<event id="GP000008" comp="GPFS">
		<message>Node recovered</message>
	</event>
	<event id="GP000009" comp="GPFS">
		<message>Filesystem created</message>
	</event>
	<event id="GP00000A" comp="GPFS">
		<message>Filesystem deleted</message>
	</event>
	<event id="GP00000B" comp="GPFS">
		<message>Filesystem state changed</message>
	</event>
	<event id="GP00000C" comp="GPFS">
		<message>New connection to GPFS monitor</message>
	</event>
	<event id="GP00000D" comp="GPFS">
		<message>Event collection buffer overflow</message>
	</event>
	<event id="GP00000E" comp="GPFS">
		<message>Token manager status</message>
	</event>
	<event id="GP00000F" comp="GPFS">
		<message>Hung thread</message>
	</event>
	<event id="GP000010" comp="GPFS">
		<message>Storage pool utilization</message>
	</event>
	<event id="GP000011" comp="GPFS">
		<message>SDR changed</message>
	</event>
	<event id="GP000012" comp="GPFS">
		<message>mmadddisk command executed</message>
	</event>
	<event id="GP000014" comp="GPFS">
		<message>Console log</message>
	</event>
	<event id="GP000015" comp="GPFS">
		<message>Long I/O time</message>
	</event>
	<event id="GP000016" comp="GPFS">
		<message>Recovery group takeover</message>
	</event>
	<event id="GP000017" comp="GPFS">
		<message>Recovery group relenquish</message>
	</event>
	<event id="GP000018" comp="GPFS">
		<message>Recovery group open failed</message>
	</event>
	<event id="GP000019" comp="GPFS">
		<message>Recovery group panic</message>
	</event>
	<event id="GP000020" comp="GPFS">
		<message>pdisk failed</message>
	</event>
	<event id="GP000021" comp="GPFS">
		<message>pdisk recovered</message>
	</event>
	<event id="GP000022" comp="GPFS">
		<message>Replace pdisk</message>
	</event>
	<event id="GP000023" comp="GPFS">
		<message>pdisk path failed</message>
	</event>
	<event id="GP000024" comp="GPFS">
		<message>Declustered array rebuild failed</message>
	</event>
	<event id="GP000025" comp="GPFS">
		<message>NSD checksum mismatch</message>
	</event>
	<event id="GP010001" comp="GPFS">
		<message>GPFS connector started</message>
	</event>
	<event id="GP010002" comp="GPFS">
		<message>GPFS connector stopped</message>
	</event>
</eventMetadata>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/gear_ruleset_test/t016/event_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>


<tns:eventMetadata xmlns:tns="http://www.ibm.com/teal/eventmeta" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ibm.com/teal/eventmeta ../../../../../xml/eventmeta.xsd ">
  <tns:event id="Event 01" comp="CNM">
    <tns:message>This is test message 1</tns:message>
  </tns:event>
  <tns:event id="Event 02" comp="CNM">
    <tns:message>This is test message 2</tns:message>
  </tns:event>
  <tns:event id="Event 03" comp="CNM">
    <tns:message>This is test message 3</tns:message>
  </tns:event>
  <tns:event id="Event 04" comp="CNM">
    <tns:message>This is test message 4</tns:message>
  </tns:event>
  <tns:event id="Event 05" comp="CNM">
    <tns:message>This is test message 5</tns:message>
  </tns:event>
  <tns:event id="Event 06" comp="CNM">
    <tns:message>This is test message 6</tns:message>
  </tns:event>
  <tns:event id="Event 07" comp="CNM">
    <tns:message>This is test message 7</tns:message>
  </tns:event>
  <tns:event id="Event 08" comp="CNM">
    <tns:message>This is test message 8</tns:message>
  </tns:event>
  <tns:event id="Event 09" comp="CNM">
    <tns:message>This is test message 9</tns:message>
  </tns:event>
  <tns:event id="Event 10" comp="CNM">
    <tns:message>This is test message 10</tns:message>
  </tns:event>
  <tns:event id="Event 11" comp="CNM">
    <tns:message>This is test message 11</tns:message>
  </tns:event>
  <tns:event id="Event 12" comp="CNM">
    <tns:message>This is test message 12</tns:message>
  </tns:event>
  <tns:event id="Event 13" comp="CNM">
    <tns:message>This is test message 13</tns:message>
  </tns:event>
  <tns:event id="Event 14" comp="CNM">
    <tns:message>This is test message 14</tns:message>
  </tns:event>
</tns:eventMetadata>
