=== ppjsand/pyteal/src/xml/extension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://www.ibm.com/teal" 
    xmlns:teal="http://www.ibm.com/teal" 
    elementFormDefault="qualified">
    
    <xsd:element name="tables" type="teal:tablesType">
                <xsd:unique name="TableIdCheck">
                    <xsd:selector xpath=".//teal:table"/>
                    <xsd:field xpath="@id"/>
                </xsd:unique>
    </xsd:element>
    
    <xsd:complexType name="tablesType">
        <xsd:sequence>
            <xsd:element name="table" type="teal:tableType" minOccurs="1" maxOccurs="unbounded">
                <xsd:unique name="ColumnIdCheck">
                    <xsd:selector xpath=".//teal:column"/>
                    <xsd:field xpath="@name"/>
                </xsd:unique>
            </xsd:element>            
        </xsd:sequence>
        <xsd:attribute name="version" type="xsd:float" use="optional"/>    
    </xsd:complexType> 

    <xsd:complexType name="tableType">
        <xsd:sequence>
            <xsd:element name="column" type="teal:columnType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="id" type="xsd:nonNegativeInteger" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="columnType">
        <xsd:attribute name="name" type="xsd:string" use="required"/> 
        <xsd:attribute name="type" use="required">                                    
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="INTEGER"/> 
                    <xsd:enumeration value="BIGINT"/>
                    <xsd:enumeration value="CHAR"/>
                    <xsd:enumeration value="VARCHAR"/>
                    <xsd:enumeration value="TEXT"/>
                    <xsd:enumeration value="LOC"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="size" type="xsd:positiveInteger" use="optional"/>
    </xsd:complexType>
        


</xsd:schema>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/ibm/teal/xml/TEST_0.xml
<?xml version="1.0" encoding="UTF-8"?>


<tables version="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../../../../../xml/extension.xsd">

    <table name="Test Data" id="0">
        <column name="info" type="VARCHAR" size="16"/>
    </table>
    
    <table name="Test Data" id="1">
        <column name="info" type="CHAR" size="18"/>
    </table>
    
    <table name="Test Data" id="2">
        <column name="info" type="CHAR" size="20"/>
    </table>
    
    <table name="Test Data" id="3">
        <column name="neighbor" type="LOC"/>
    </table>

    <table name="Test Data" id="4">
        <column name="number" type="INTEGER"/>
    </table>

    <table name="Test Data" id="5">
        <column name="number" type="BIGINT"/>
    </table>
</tables>

=== ppjsand/pyteal/src/data/ibm/teal/xml/GPFS_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<tables xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../xml/extension.xsd ">

    <table name="filesystem" id="1">
        <column name="severity" type="VARCHAR" size="256"/>
        <column name="node_ip" type="VARCHAR" size="256"/>
        <column name="sgmgr_ip" type="VARCHAR" size="256"/>
        <column name="user_unba" type="VARCHAR" size="256"/>
        <column name="meta_unba" type="VARCHAR" size="256"/>
        <column name="user_ill_rep" type="VARCHAR" size="256"/>
        <column name="meta_ill_rep" type="VARCHAR" size="256"/>
        <column name="user_exposed" type="VARCHAR" size="256"/>
        <column name="meta_exposed" type="VARCHAR" size="256"/>
        <column name="pool_name" type="VARCHAR" size="256"/>
        <column name="pool_status" type="VARCHAR" size="256"/>
        <column name="pool_usage" type="INTEGER"/>
    </table>
    
    <table name="disk" id="2">
        <column name="severity" type="VARCHAR" size="256"/>
        <column name="fs_name" type="VARCHAR" size="256"/>
        <column name="node_name" type="VARCHAR" size="256"/>
        <column name="node_ip" type="VARCHAR" size="256"/>
        <column name="status" type="VARCHAR" size="256"/>
        <column name="availability" type="VARCHAR" size="256"/>
        <column name="fg_name" type="VARCHAR" size="256"/>
        <column name="meta" type="VARCHAR" size="256"/>
        <column name="data" type="VARCHAR" size="256"/>
        <column name="cmd" type="VARCHAR" size="256"/>
        <column name="my_role" type="VARCHAR" size="256"/>
        <column name="ck_reason" type="VARCHAR" size="256"/>
        <column name="other_node" type="VARCHAR" size="256"/>
        <column name="data_len" type="INTEGER"/>
        <column name="err_cnt_client" type="INTEGER"/>
        <column name="err_cnt_serv" type="INTEGER"/>
        <column name="err_cnt_nsd" type="INTEGER"/>
        <column name="rpt_interval" type="INTEGER"/>
        <column name="io_length" type="INTEGER"/>
        <column name="io_time" type="INTEGER"/>
        <column name="start_sector" type="BIGINT"/>
    </table>
    
    <table name="perseus" id="3">
        <column name="severity" type="VARCHAR" size="256"/>
        <column name="node_name" type="VARCHAR" size="256"/>
        <column name="location" type="VARCHAR" size="256"/>
        <column name="fru" type="VARCHAR" size="256"/>
        <column name="wwn" type="VARCHAR" size="256"/>
        <column name="state" type="VARCHAR" size="256"/>
        <column name="priority" type="INTEGER"/>
    </table>
    
    <table name="misc" id="4">
        <column name="severity" type="VARCHAR" size="256"/>
        <column name="msg_text" type="VARCHAR" size="256"/>
        <column name="diagnosis" type="VARCHAR" size="256"/>
        <column name="wait_time" type="VARCHAR" size="256"/>
        <column name="msg_level" type="INTEGER"/>
    </table>
</tables>
