=== ppjsand/pyteal/src/xml/location.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:teal="http://www.ibm.com/teal"
    targetNamespace="http://www.ibm.com/teal"
    elementFormDefault="qualified"
    >
    
    <!--
        This schema defines the sets of Location codes for a cluster.
        
        Location codes are hierarchical by nature and made up of components.
        A Location code can be considered "simple" or "complex" based on the needs of the user
        
        A simple Location code uses free-form text for each component and is a simple hierarchy with
        one component per level.
        
        A complex Location code uses a short-hand alpha key value followed by an optional number for
        each of its components. Each component may have any number of child components as well. Complex
        Location codes are typically used to model hardware topology within a system                
     -->
     
    <!-- 
        The cluster element is the top level element with in the document and contains a number of
        different location code types. Each location code type and id must be unique within the cluster.        
     --> 
    <xsd:element name="cluster" type="teal:clusterType">
        <xsd:unique name="LocationCondition">
            <xsd:selector xpath=".//teal:location"/>
            <xsd:field xpath="@id"/>
        </xsd:unique>
        <xsd:unique name="TypeCondition">
            <xsd:selector xpath=".//teal:location"/>
            <xsd:field xpath="@type"/>
        </xsd:unique>        
    </xsd:element>                    
     
     <!--    
             Similarly to the location, each component and its type must be unique within a location code
      -->        
    <xsd:complexType name="clusterType">
        <xsd:sequence>
            <xsd:element name="location" type="teal:locationType"  minOccurs="1" maxOccurs="unbounded">
                <xsd:unique name="CompTypeCondition">
                    <xsd:selector xpath=".//*/teal:component"/>
                    <xsd:field xpath="@type"/>
                </xsd:unique>
                <xsd:unique name="RefCondition">
                    <xsd:selector xpath=".//*/teal:component/teal:compref"/>
                    <xsd:field xpath="@ref"/>
                </xsd:unique>
                <xsd:key name="componentTypeId">
                    <xsd:selector xpath=".//*/teal:component"/>
                    <xsd:field xpath="@type"/>
                </xsd:key>
                <xsd:keyref name="componentIdRef" refer="teal:componentTypeId">
                    <xsd:selector xpath=".//*/teal:component/teal:compref"/>
                    <xsd:field xpath="@ref"/>
                </xsd:keyref>
            </xsd:element>        
        </xsd:sequence>
        <xsd:attribute name="ver" type="xsd:float" use="required"/>
    </xsd:complexType>
        
    <xsd:complexType name="locationType">
        <xsd:choice>
            <xsd:element name="simple" type="teal:simpleType"/>
            <xsd:element name="complex" type="teal:complexType"/>
        </xsd:choice>
        <!-- The ID is used to identify the type of Location Code this is within the TEAL framework and database tables -->        
        <xsd:attribute name="id"        use="required" type="teal:identType"/>
        <!-- The type of Location code this is within the cluster -->
        <xsd:attribute name="type"      use="required" type="xsd:string"/>
        <!-- string separator when displaying and parsing the components of a location code -->
        <xsd:attribute name="separator" use="optional" default="." type="xsd:string"/> 
    </xsd:complexType>
    
    <!-- 
        Simple Location code content is described by a list of components. The order that the components are
        defined within this section describes the hierarchy of the Location code. There is a one-one 
        parent-child correspondence  
     -->
    <xsd:complexType name="simpleType">
        <xsd:sequence>
            <xsd:element name="component" type="teal:simpleComponentType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <!--
        Complex Location code content is a tree structure and is displayed as short-hand ID with an optional
        instance value. 
     -->
    <xsd:complexType name="complexType">
        <xsd:sequence>
            <xsd:element name="component" type="teal:complexComponentType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="simpleComponentType">
        <xsd:attribute name="type"/> <!-- Type is the only requirement of a simple Location code component -->
    </xsd:complexType>
    
    <xsd:complexType name="complexComponentType">
        <xsd:sequence>
            <xsd:element name="compref" type="teal:componentRefType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <!--  Must have a unique type for each level -->
        <xsd:attribute name="type" use="required" type="xsd:string"/> 
        <!-- Each level will have a simple 1-2 character ID. It is not necessary to be unique within the Location code -->
        <xsd:attribute name="id" type="teal:identType" use="required"/> 
        <!-- 
            A min and max value may be specified by the user. For a range of valid values. 
            
            If neither min nor max are specified, then the component has NO value, only an identifier.
            If min is only specified, then max is the size of the largest int representation on the system
            If max is only specified, then min is defaulted to 0
            If both max and min are specified, it must be true that min <= max
        -->   
        <!-- xsd:attribute name="min" type="xsd:nonNegativeInteger" use="optional"/ -->
        <!-- xsd:attribute name="max" type="xsd:nonNegativeInteger" use="optional"/ -->
        <xsd:attribute name="pattern" type="xsd:token" use="optional"/>
    </xsd:complexType>
    
    <!--
        A component reference element is used to describe which components are a child of the current component. 
     -->
    <xsd:complexType name="componentRefType">
        <xsd:attribute name="ref" type="xsd:string"/>
    </xsd:complexType>
    
    <!--
        An identity string is a one or two uppercase character string. 
     -->
    <xsd:simpleType name="identType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z]{1,2}"/>    
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/gear_ruleset_test/t999/percs_location.xml
<?xml version="1.0" encoding="UTF-8"?>


<cluster ver="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../xml/location.xsd ">
  
    <location id="D" type="device" separator="##">
        <simple>
            <component type="node"/>
            <component type="device"/>
            <component type="major"/>
            <component type="minor"/>
        </simple>
    </location>

    <location id="A" type="application" separator="##">
        <simple>
            <component type="node"/>            
            <component type="application"/>
            <component type="pid"/>
            <component type="identifier"/>
        </simple>
    </location>

    <location id="J" type="job" separator="##">
        <simple>
            <component type="stepId"/>
            <component type="node"/>
            <component type="task"/>
        </simple>
    </location>

    <location id="F" type="frame" separator="-">
        <complex>
            <component type="frame" id="FR" min="0">
                <compref ref="cage"/>
            </component>    
            <component type="cage" id="CG" min="1" max="32"/>
        </complex>
    </location>

    <location id="H" type="hardware" separator="-">
        <complex>
            <!-- Level 1 -->
            <component type="buildingBlock" id="BB" min="1" max="65">
                <compref ref="frame" />

            <!-- Level 2 -->
            </component><component type="frame" id="SN" min="1" max="193">
                <compref ref="supernode"/>
            </component>

            <!-- Level 3 -->
            <component type="supernode" id="SN" min="1" max="512">
                <compref ref="drawer"/>
            </component>

            <!-- Level 4 -->
            <component type="drawer" id="DR" min="1" max="12">            
                    <compref ref="hub"/>
            </component>        

            <!-- Level 5 -->
            <component type="hub" id="HB" min="1" max="8">
                <compref ref="localPort"/>
                <compref ref="remotePort"/>
                <compref ref="nodePort"/>
            </component>

            <!-- Level 6 -->
            <component type="localPort" id="LL" min="1" max="8"/>
            <component type="remotePort" id="LR" min="1" max="32"/>
            <component type="nodePort" id="LD" min="1" max="16"/>

        </complex>
    </location>
    
    <location id="P" type="pseries" separator="-">
        <complex>
            <!-- Level 1 -->            
            <component type="frame" id="U" min="1">
                <compref ref="epoPanel"/>
                <compref ref="bpa"/>
                <compref ref="wcu"/>
                <compref ref="fdt"/>
                <compref ref="p7ih"/>
                <compref ref="diskEnclosure"/>
            </component>
            
            <!-- Level 2 --> 
            <component type="epoPanel" id="D" min="1" max="1">
                <compref ref="bpaConnector"/>
            </component>
            <component type="bpa" id="P" min="1" max="2">
                <compref ref="lineCord"/>
                <compref ref="bpr"/>
                <compref ref="bpf"/>
                <compref ref="bpch"/>
                <compref ref="bpd"/>
            </component>                               
            <component type="wcu" id="P" min="3" max="6">
                <compref ref="mda"/>
            </component>
            <component type="fdt" id="P" min="7" max="8">
                <compref ref="fdtControlCard"/>
            </component>
            <component type="diskEnclosure" id="DE" min="1" max="6">
                <compref ref="dca"/>
                <compref ref="backplane"/>                
            </component>
            
            <!-- Level 3 -->                
            <component type="p7ih" id="DR" min="1" max="12">
                <compref ref="processorFru"/>
            </component>
            <component type="bpaConnector" id="T" min="1" max="2"/>
            <component type="lineCord" id="J" min="1" max="2"/>
            <component type="bpr" id="E" min="1" max="6"/>
            <component type="bpf" id="A" min="1" max="4"/>
            <component type="bpch" id="C" min="1" max="1">
                <compref ref="bpchConnector"/>
            </component>    
            <component type="bpd" id="C" min="2" max="2">
                <compref ref="bpdConnector"/>
            </component>
            <component type="mda" id="C" min="1" max="1">
                <compref ref="mdaConnector"/>
            </component>    
            <component type="fdtControlCard" id="C" min="1" max="1"/>
            <component type="dca" id="E" min="1" max="2">
                <compref ref="upicConnector"/>
            </component> 
            <component type="backplane" id="P" min="1" max="3">
                <compref ref="fan"/>
                <compref ref="carrier"/>
                <compref ref="portCard"/>
            </component>
            
            <!-- Level 4 -->
            <component type="bpchConnector" id="T" min="1" max="42"/>
            <component type="bpdConnector" id="T" min="1" max="26"/>
            <component type="mdaConnector" id="T" min="1" max="2"/>
            <component type="processorFru" id ="P" min="1" max="1">
                <compref ref="dcca" />
                <compref ref="vpd"/>
                <compref ref="dimm"/>
                <compref ref="pciRiser"/>
                <compref ref="procModule"/>
                <compref ref="ioModule"/>
            </component>
            <component type="upicConnector" id="T" min="1" max="2"/> 
            <component type="fan" id="A" min="1" max="12"/>
            <component type="carrier" id="C" min="1" max="56">
                <compref ref="drive"/>
            </component>
            <component type="portCard" id="C" min="4" max="29">
                <compref ref="sasPort"/>
            </component>    
            
            <!-- Level 5 -->
            <component type="dcca" id="C" min="147" max="148">
                <compref ref="hmcConnector"/>
                <compref ref="dccaConnector"/>
                <compref ref="battery"/>
            </component>
            <component type="vpd" id="C" min="146" max="146"/>
            <component type="dimm" id="C" min="18" max="145"/>
            <component type="pciRiser" id="C" min="1" max="17">
                <compref ref="pciSlot"/>
            </component>
            <component type="procModule" id="PM" min="0" max="7">
                <compref ref="processor"/>
            </component>
            <component type="ioModule" id="IM" min="0" max="7">
                <compref ref="ioHub"/>
            </component>
            <component type="drive" id="D" min="1" max="4"/>   
            <component type="sasPort" id="T" min="1" max="4"/>   
                
            <!-- Level 6 -->
            <component type="pciSlot" id="C" min="1" max="1"/>
            <component type="processor" id="PR" min="0" max="3"/>
            <component type="ioHub" id="IH" min="0" max="3">
                <compref ref="lrLink"/>
                <compref ref="dLinks"/>
            </component>
                
            <component type="hmcConnector" id="T" min="2" max="3"/>
            <component type="dccaConnector" id="T" min="1" max="4"/>
            <component type="battery" id="E" min="1" max="1"/>

            <!-- Level 7 -->
            <component type="dLinks" id="T" min="1" max="17">
                <compref ref="dLink"/>
            </component>
            <component type="lrLink" id="T" min="9" max="9"/>
            
            <!-- Level 8 -->    
            <component type="dLink" id="T" min="1" max="8"/>
        </complex>    
    </location>
    
</cluster>

=== ppjsand/pyteal/src/data/ibm/teal/xml/percs_location.xml
<?xml version="1.0" encoding="UTF-8"?>


<cluster ver="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../xml/location.xsd ">
  
    <location id="D" type="device" separator="##">
        <simple>
            <component type="node"/>
            <component type="device"/>
            <component type="major"/>
            <component type="minor"/>
        </simple>
    </location>

    <location id="A" type="application" separator="##">
        <simple>
            <component type="node"/>            
            <component type="application"/>
            <component type="pid"/>
            <component type="identifier"/>
        </simple>
    </location>

    <location id="J" type="job" separator="##">
        <simple>
            <component type="stepId"/>
            <component type="node"/>
            <component type="task"/>
        </simple>
    </location>

    <location id="H" type="hardware" separator="-">
        <complex>
            <!-- Level 1 -->
            <component type="frame" id="FR" pattern="00[1-9]|0[1-9][0-9]|[1-9][0-9][0-9]">
                <compref ref="cage"/>
            </component>

            <!-- Level 2 -->
            <component type="cage" id="CG" pattern="0[3-9]|1[0-4]">
                <compref ref="supernode"/>
            </component>
            
            <!-- Level 3 -->
            <component type="supernode" id="SN" pattern="[0-4][0-9][0-9]|50[0-9]|51[0-1]">
                <compref ref="drawer"/>
            </component>

            <!-- Level 4 -->
            <component type="drawer" id="DR" pattern="[0-3]">            
                    <compref ref="hub"/>
            </component>        

            <!-- Level 5 -->
            <component type="hub" id="HB" pattern="[0-7]">
                <compref ref="localPort"/>
                <compref ref="remotePort"/>
                <compref ref="nodePort"/>
                <compref ref="hfi"/>
                <compref ref="opticalModule"/>
            </component>

            <!-- Level 6 -->
            <component type="localPort" id="LL" pattern="0[0-6]"/>
            <component type="opticalModule" id="OM" pattern="[0-1][0-9]|2[0-7]">
                <compref ref="remotePort"/>
                <compref ref="nodePort"/>
            </component>
            <component type="hfi" id="HF" pattern="[0-1]">
                <compref ref="ramp"/>
            </component>
            
            <!-- Level 7 -->
            <component type="remotePort" id="LR" pattern="[0-1][0-9]|2[0-3]"/>
            <component type="nodePort" id="LD" pattern="0[0-9]|1[0-5]"/>
            <component type="ramp" id="RM" pattern="[0-3]"/>

        </complex>
    </location>
    <location id="P" type="pseries" separator="@">
    	<simple>
    		<component type="ploc"/>
    	</simple>
    </location>
    <location id="G" type="gpfs" separator="|">
    	<complex>
	        <!-- Level 1 -->
	        <component type="cluster" id="C" pattern=":.+">
	            <compref ref="filesystem"/>
	            <compref ref="disk"/>
	            <compref ref="recoveryGroup"/>
	            <compref ref="node"/>
	        </component>
	
	        <!-- Level 2 -->
	        <component type="filesystem" id="FS" pattern=":.+">
	            <compref ref="storagePool"/>
	            <compref ref="fileSet"/>
	        </component>
	        <component type="disk" id="DK" pattern=":.+"/>
	        <component type="recoveryGroup" id="RG" pattern=":.+">
	            <compref ref="declusteredArray"/>
	        </component>
	        <component type="node" id="N" pattern=":.+"/>
	        
	        <!-- Level 3 -->
	        <component type="storagePool" id="SP" pattern=":.+"/>
	        <component type="fileSet" id="FT" pattern=":.+"/>
	        <component type="declusteredArray" id="DA" pattern=":.+">
	            <compref ref="pdisk"/>
	            <compref ref="vdisk"/>
	        </component>
	        
	        <!-- Level 4 -->
	        <component type="pdisk" id="PD" pattern=":.+"/>
	        <component type="vdisk" id="VD" pattern=":.+"/>
		</complex>
    </location>
    <location id="U" type="ufm" separator="|">
    	<complex>
		    <!-- Level 1 -->
		    <component type="site" id="S" pattern=":.+">
			    <compref ref="switch"/>
		    	<compref ref="computer"/>
		    	<compref ref="gateway"/>
		    	<compref ref="vm"/>
		    	<compref ref="vmm"/>
		    </component>
		    
		    <!-- Level 2 -->
		    <component type="switch" id="SW" pattern=":.+">
		    	<compref ref="swport"/>
		    	<compref ref="line"/>
		    	<compref ref="spine"/>
		      	<compref ref="psu"/>
		      	<compref ref="smb"/>
		      	<compref ref="fan"/>
		    </component>
		    <component type="computer" id="C" pattern=":.+">
		    	<compref ref="cport"/>
		    </component>
		    <component type="gateway" id="GW" pattern=":.+"/>
		    <component type="vm" id="VM" pattern=":.+"/>
		    <component type="vmm" id="V" pattern=":.+"/>
		
		    <!-- Level 3 -->
		    <component type="cport" id="P" pattern=":.+"/>
		    <component type="swport" id="P" pattern=":.+"/>
		    <component type="line" id="P" pattern=":.+">
		    	<compref ref="lport"/>
		    </component>
		    <component type="spine" id="SP" pattern=":.+">
		    	<compref ref="spport"/>
		    </component>
		    <component type="psu" id="PS" pattern=":.+"/>
		    <component type="smb" id="SM" pattern=":.+"/>
		    <component type="fan" id="F" pattern=":.+"/>
		    
		    <!-- Level 4 -->
		    <component type="lport" id="P" pattern=":.+"/>
		    <component type="spport" id="P" pattern=":.+"/>
	    </complex>	    
    </location> 
</cluster>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/location_test/locationtest_01.xml
<?xml version="1.0" encoding="UTF-8"?>


<cluster ver="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../../xml/location.xsd">
    <location id="TS" type="test_simple">
        <simple>
            <component type="parent"/>
            <component type="child"/>
            <component type="grandchild"/>
        </simple>
    </location>  
    <location id='TC' type="test_complex" separator="-">
        <complex>
            <component type="top" id="R">
                <compref ref="home"/>
            </component>
            <component type="home" id="H">
                <compref ref="psanders"/>
                <compref ref="markland"/>
                <compref ref="jecarey"/>
                <compref ref="kilroy"/>
            </component>
            <component type="psanders" id="PS" pattern="[1-9]|10"/>
            <component type="markland" id="MM" min="5" pattern="[5-9]|[1-9][0-9]+"/>
            <component type="jecarey"  id="JC"/>
            <component type="kilroy"   id="K" pattern="[0-9]|1[0-9]|20">
                <compref ref="src"/>
            </component>
            <component type="src" id="S"/>    
        </complex>
    </location>         
</cluster>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/location_test/locationtest_03.xml
<?xml version="1.0" encoding="UTF-8"?>


<cluster ver="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../../xml/location.xsd">
    <location id="TS" type="test_simple">
        <simple>
            <component type="parent"/>
            <component type="child"/>
            <component type="grandchild"/>
        </simple>
    </location>  
    <location id='TC' type="test_complex" separator="-">
        <complex>
            <component type="top" id="R">
                <compref ref="home"/> 
            </component>
            <component type="home" id="H">
                <compref ref="psanders"/>
                <compref ref="markland"/>
                <compref ref="jecarey"/>
                <compref ref="kilroy"/>
            </component>
            <component type="psanders" id="PS" min="1" max="10"/>
            <component type="markland" id="MM" min="5"/>
            <component type="jecarey"  id="JC"/>
            <component type="kilroy"   id="K" max="20">
                <compref ref="src"/>
                <compref ref="top"/> <!-- No root -->
            </component>
            <component type="src" id="S"/>    
        </complex>
    </location>         
</cluster>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/gear_ruleset_test/t001/percs_location.xml
<?xml version="1.0" encoding="UTF-8"?>


<cluster ver="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../xml/location.xsd ">
  
    <location id="D" type="device" separator="##">
        <simple>
            <component type="node"/>
            <component type="device"/>
            <component type="major"/>
            <component type="minor"/>
        </simple>
    </location>

    <location id="A" type="application" separator="##">
        <simple>
            <component type="node"/>            
            <component type="application"/>
            <component type="pid"/>
            <component type="identifier"/>
        </simple>
    </location>

    <location id="J" type="job" separator="##">
        <simple>
            <component type="stepId"/>
            <component type="node"/>
            <component type="task"/>
        </simple>
    </location>

    <location id="H" type="hardware" separator="-">
        <complex>
            <!-- Level 1 -->
            <component type="buildingBlock" id="BB" pattern="[0-5][0-9]|6[0-4]">
                <compref ref="frame" />

            <!-- Level 2 -->
            </component><component type="frame" id="FR" pattern="00[1-9]|0[1-9][0-9]|[1-9][0-9][0-9]">
                <compref ref="supernode"/>
            </component>

            <!-- Level 3 -->
            <component type="supernode" id="SN" pattern="[0-4][0-9][0-9]|50[0-9]|51[0-1]">
                <compref ref="drawer"/>
            </component>

            <!-- Level 4 -->
            <component type="drawer" id="DR" pattern="[0-3]">            
                    <compref ref="hub"/>
            </component>        

            <!-- Level 5 -->
            <component type="hub" id="HB" pattern="[0-7]">
                <compref ref="localPort"/>
                <compref ref="remotePort"/>
                <compref ref="nodePort"/>
            </component>

            <!-- Level 6 -->
            <component type="localPort" id="LL" pattern="0[0-7]"/>
            <component type="remotePort" id="LR" pattern="[0-2][0-9]|3[0-1]"/>
            <component type="nodePort" id="LD" pattern="0[0-9]|1[0-5]"/>

        </complex>
    </location>
    <location id="P" type="pseries" separator="@">
    	<simple>
    		<component type="ploc"/>
    	</simple>
    </location>
</cluster>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/common/locationtest.xml
<?xml version="1.0" encoding="UTF-8"?>


<cluster ver="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../../xml/location.xsd">
    
    <location id="S" type="application" separator="##">
        <simple>
            <component type="node"/>            
            <component type="application"/>
            <component type="pid"/>
        </simple>
    </location>

    <location id="C" type="test_complex" separator="-">
        <complex>
            <component type="motherboard" id="MB">
                <compref ref="processor"/>
                <compref ref="dimm"/>
                <compref ref="pciSlot"/>
            </component>
            <component type="processor" id="PR" pattern="[1-4]"/>
            <component type="dimm" id="DM" pattern="[1-9]|1[0-6]"/>
            <component type="pciSlot" id="SL" pattern="[1-4]">
                <compref ref="ethernetCard"/>                
            </component>
            <component type="ethernetCard" id="ET" pattern="1">
                <compref ref="port"/>                
            </component>                            
            <component type="port" id="PT" pattern="[1-2]"/>
        </complex>
    </location>
    
    <location id="A" type="application" separator="##">
        <simple>
            <component type="node"/>            
            <component type="application"/>
            <component type="pid"/>
            <component type="identifier"/>
        </simple>
    </location>
    
</cluster>

=== ppjsand/pyteal/src/ibm/teal/test/ut/data/gear_ruleset_test/t044/locationtest.xml
<?xml version="1.0" encoding="UTF-8"?>


<cluster ver="1.0"
    xmlns="http://www.ibm.com/teal" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.ibm.com/teal ../../../../../xml/location.xsd">
    
    <location id="S" type="application" separator="##">
        <simple>
            <component type="node"/>            
            <component type="application"/>
            <component type="pid"/>
        </simple>
    </location>

    <location id="C" type="test_complex" separator="-">
        <complex>
            <component type="motherboard" id="MB">
                <compref ref="processor"/>
                <compref ref="dimm"/>
                <compref ref="pciSlot"/>
            </component>
            <component type="processor" id="PR" min="1" max="4"/>
            <component type="dimm" id="DM" min="1" max="16"/>
            <component type="pciSlot" id="SL" min="1" max="4">
                <compref ref="ethernetCard"/>                
            </component>
            <component type="ethernetCard" id="ET" min="1" max="1">
                <compref ref="port"/>                
            </component>                            
            <component type="port" id="PT" min="1" max="22"/>
        </complex>
    </location>
    
</cluster>
